/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTinyRouteImport } from './routes/_authenticated/tiny'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedLotesRouteImport } from './routes/_authenticated/lotes'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedEtiquetaAvulsaRouteImport } from './routes/_authenticated/etiqueta-avulsa'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTinyRoute = AuthenticatedTinyRouteImport.update({
  id: '/tiny',
  path: '/tiny',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLotesRoute = AuthenticatedLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtiquetaAvulsaRoute =
  AuthenticatedEtiquetaAvulsaRouteImport.update({
    id: '/etiqueta-avulsa',
    path: '/etiqueta-avulsa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/etiqueta-avulsa': typeof AuthenticatedEtiquetaAvulsaRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/lotes': typeof AuthenticatedLotesRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tiny': typeof AuthenticatedTinyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/etiqueta-avulsa': typeof AuthenticatedEtiquetaAvulsaRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/lotes': typeof AuthenticatedLotesRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tiny': typeof AuthenticatedTinyRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/etiqueta-avulsa': typeof AuthenticatedEtiquetaAvulsaRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/lotes': typeof AuthenticatedLotesRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tiny': typeof AuthenticatedTinyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/etiqueta-avulsa'
    | '/importar'
    | '/lotes'
    | '/movimentacoes'
    | '/orcamento'
    | '/precos'
    | '/relatorios'
    | '/tiny'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/etiqueta-avulsa'
    | '/importar'
    | '/lotes'
    | '/movimentacoes'
    | '/orcamento'
    | '/precos'
    | '/relatorios'
    | '/tiny'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/catalogo'
    | '/_authenticated/configuracoes'
    | '/_authenticated/etiqueta-avulsa'
    | '/_authenticated/importar'
    | '/_authenticated/lotes'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/orcamento'
    | '/_authenticated/precos'
    | '/_authenticated/relatorios'
    | '/_authenticated/tiny'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tiny': {
      id: '/_authenticated/tiny'
      path: '/tiny'
      fullPath: '/tiny'
      preLoaderRoute: typeof AuthenticatedTinyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lotes': {
      id: '/_authenticated/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AuthenticatedLotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiqueta-avulsa': {
      id: '/_authenticated/etiqueta-avulsa'
      path: '/etiqueta-avulsa'
      fullPath: '/etiqueta-avulsa'
      preLoaderRoute: typeof AuthenticatedEtiquetaAvulsaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEtiquetaAvulsaRoute: typeof AuthenticatedEtiquetaAvulsaRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedLotesRoute: typeof AuthenticatedLotesRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTinyRoute: typeof AuthenticatedTinyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEtiquetaAvulsaRoute: AuthenticatedEtiquetaAvulsaRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedLotesRoute: AuthenticatedLotesRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTinyRoute: AuthenticatedTinyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
